---
- name: Install WEB-server
  hosts: all
  become: yes

  vars:
    source_file: /home/engineer/ansible/index.html
    destin_file: /var/www/html/
    _package: "{{'apache2' if ansible_os_family == 'Debian' or 'httpd'}}"
    
  tasks:
  - name: Install Apache
    package: name={{_package}}
  - copy: src={{source_file}} dest={{destin_file}} mode=0644
    notify: Restart Apache
  - name: Start Apache
    service: name={{_package}} state=started enabled=yes
  
  handlers:
  - name: Restart Apache
    service: name={{_package}} state=restarted
