---
- name: Install Latest PostgreSQL
  hosts: all
  become: yes
  vars:
    # Укажите желаемую мажорную версию (16 - последняя на момент написания)
    pg_version: "17"
    
  tasks:
    - name: clean repo
      file:
        path: /etc/apt/sources.list.d/pgdg.list
        state: absent

    - name: Install prerequisites (Debian)
      apt:
        name:
          - gnupg
          - curl
          - software-properties-common
        state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: Add PostgreSQL GPG key (Debian)
      apt_key:
        url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
        state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: Add PostgreSQL repository (Debian)
      apt_repository:
        repo: "deb https://apt.postgresql.org/pub/repos/apt {{ ansible_facts['distribution_release'] }}-pgdg main"
        state: present
        filename: "postgresql"
      when: ansible_facts['os_family'] == "Debian"

    - name: Install PostgreSQL (Debian)
      apt:
        name: "postgresql-{{ pg_version }}"
        state: latest
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"

  
 
