---
- name: Loops Playbook
  hosts: client1
  become: yes
  gather_facts: false

  tasks:
  - name: say Hello
    debug: msg="Hello {{item}}"
    loop:
      - "Ivan"
      - "Andrey"
      - "Alexey"
  
  - name: loop until
    shell: echo -n Z >> myfile.txt && cat myfile.txt
    register: output
    delay: 3
    retries: 10
    until: output.stdout.find("ZZZZZ") == false
  
  - debug:
      var: output.stdout
  
