---
# tasks file for postgresql
- name: install postgresql
  apt: 
    name: 
      - "postgresql-{{postgresql_version}}"
      - python3-psycopg2
    state: present
    update_cache: yes

- name: conf pg service
  service: name=postgresql state=started enabled=yes

- name: set listener
  lineinfile:
    path: "{{postgresql_conf_path}}"
    regexp: '^#?listen_addresses'
    line: "listen_addresses = {{postgresql_listen_addresses}}" 
  notify: Restart Postgresql

- name: allow connection
  lineinfile:
    path: "{{pg_hba_conf_path}}"
    regexp: '^host\s+{{db_name}}\s{{db_user}}'
    line: "host {{db_name}} {{db_user}} 127.0.0.1/32 md5"
    create: yes
    insertafter: EOF
  notify: Restart Postgresql

- name: Create DB
  become_user: postgres
  postgresql_db: name={{db_name}} state=present

- name: Create user
  become_user: postgres
  postgresql_user: name={{db_user}} password={{db_password}} state=present

- name: grant privileges
  become_user: postgres
  postgresql_privs:
    db: "{{db_name}}"
    roles: "{{db_user}}"
    privs: ALL
    type: database
