#SPDX-License-Identifier: MIT-0
---
# tasks file for nginx-deploy
- name: OS test
  fail:
    msg: Эта роль поддерживает только Debian/Ubuntu or RedHat
  when: >
    ansible_os_family not in ["Debian","RedHat","RED"] or
    ansible_distribution not in ["Ubuntu","Debian","RED"]

- name: Проверка сетевого порта
  fail: 
    msg: Порт должен быть в диапозоне 1-65535
  when: nginx_port is not number or nginx_port <1 or nginx_port > 65535

- name: Установка nginx
  package:
    name: nginx
    state: present
  when: ansible_os_family == "Debian"
  notify: restart nginx

- name: nginx-root create
  file:
    path: "{{nginx_root}}"
    state: directory
    owner: "{{nginx_user}}"
    mode: 0755
  when: nginx_root is defined and nginx_root is not none

- name: test user
  user:
    name: "{{nginx_user}}"
    state: present
  when: nginx_user is defined

- name: generate config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    backup: yes
    validate: "nginx -t -c %s"
  notify: restart nginx

- name: generate test-page
  copy:
    content: "<html><body><h1>Nginx работает!</h1><p> Server: {{ansible_hostname}}</p></body></html>"
    dest: "{{nginx_root}}/index.html"
    owner: "{{nginx_user}}"
    mode: 0644
  when: nginx_create_test_page is defined
  notify: restart nginx

- service: name=nginx state=started enabled=yes

#- name: nginx test
#  uri:
#    url: "http://localhost:{{nginx_port}}/"
#    status_code: 200
#  register: nginx_check
#  when: nginx_create_test_page