---
- name: deploy wp, pg, nginx
  hosts: my_deb
  become: yes

  vars:
    wp_domain: "ansible.ru"
    wp_root: "/var/www/{{wp_domain}}"
    db_name: wordpress
    db_user: wp_user
    db_password: MySuperPass
    db_host: localhost
    php_fpm_pool: www
    wp_admin_email: iklimarev@gmail.com
    wp_admin_user: admin
    wp_admin_pass: adminpass
    wp_title: "My WordPress Site"
    
  roles:
    - role: postgresql
      vars:
        postgresql_version: "17"
        postgresql_conf_path: /etc/postgresql/{{postgresql_version}}/main/postgresql.conf
        pg_hba_conf_path: /etc/postgresql/{{postgresql_version}}/main/pg_hba.conf
        postgresql_listen_addresses: localhost
    - role: wordpress
    - role: nginx