---
# tasks file for wordpress
- name: install php and wp
  apt:
    name:
     - php
     - php-fpm
     - php-pgsql
     - php-mbstring
     - php-xml
     - php-gd
     - unzip
    state: present
    update_cache: yes

- name: Download PostgreSQL for WordPress plugin
  get_url:
    url: https://github.com/PostgreSQL-For-Wordpress/postgresql-for-wordpress/archive/refs/tags/v3.3.1.zip
    dest: /tmp/pg4wp.zip
    mode: 0644

- name: Extract PostgreSQL plugin
  unarchive:
    src: /tmp/pg4wp.zip
    dest: "{{ wp_root }}/wp-content/plugins/"
    remote_src: yes
    creates: "{{ wp_root }}/wp-content/plugins/postgresql-for-wordpress"

- name: Gather package facts
  package_facts:
    manager: auto

- name: Extract clean PHP version
  set_fact:
    php_version_clean: "{{ ansible_facts.packages['php'][0]['version'] | regex_replace('^(.*:)?([0-9]+\\.[0-9]+).*$', '\\2') }}"
  when: "'php' in ansible_facts.packages"

- name: config php
  service:
    name: "php{{ php_version_short | default('8.2') }}-fpm"
    state: started
    enabled: yes

- name: create root
  file:
    path: "{{wp_root}}"
    state: directory
    owner: www-data
    group: www-data
    mode: 0755

- name: download and unzip wordpress
  unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: /tmp
    remote_src: yes

- name: copy wp to root
  copy:
    src: /tmp/wordpress/
    dest: "{{wp_root}}"
    remote_src: yes
    owner: www-data
    group: www-data
    mode: 0755

- name: configure wp-config.php
  template:
    src: wp-config.php.j2
    dest: "{{wp_root}}"
    owner: www-data
    group: www-data
    mode: 0644