---
- name: Install Web-server and upload web-site
  hosts: my_deb
  become: yes

  vars:
    source_file: /home/engineer/ansible/index.html
    destin_file: /var/www/html
  
  tasks:
  - name: Install Apache
    apt:
      name: apache2
      state: latest
  
  - name: Copy WEB-site
    copy: src={{ source_file }} dest={{ destin_file }} mode=0555
    notify: Restart Apache
  
  - name: Start Apache
    service:
      name: apache2
      state: started
      enabled: yes
  
  handlers: 
  - name: Restart Apache
    service:
      name: apache2
      state: restarted