---
# tasks file for nginx
- name: install nginx
  apt: name=nginx state=present update_cache=yes

- name: config nginx service
  service: name=nginx state=started enabled=yes

- name: generate site
  template:
    src: wordpress-nginx.conf.j2
    dest: "/etc/nginx/sites-available/{{wp_domain}}"

- name: enable nginx site
  file:
    src: "/etc/nginx/sites-available/{{wp_domain}}"
    dest: "/etc/nginx/sites-enabled/{{wp_domain}}"
    state: link
    force: yes

- name: remove default site
  file: 
    path: "/etc/nginx/sites-enabled/default"
    state: absent

- name: reload nginx
  service: name=nginx state=reloaded